kind: pipeline
name: default

steps:
- name: docker
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: ironcore864/go-hello-http
    tags: latest
