dist: xenial

os: linux

language: go

services:
  - docker

before_install:
  - docker build -t ironcore864/go-hello-http .

deploy:
  provider: script
  script: bash travis/docker_push
  on:
    branch: master
