dist: xenial

os: linux

language: go

go:
  - 1.15.x

services:
  - docker

script:
  - go test -v ./...
  - travis/docker_build_push.sh

deploy:
  provider: script
  script: bash travis/docker_build_push.sh
