dist: xenial

os: linux

language: go

go:
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - 1.13.x

services:
  - docker

script:
  - go test -v ./...

deploy:
  provider: script
  script: bash travis/docker_build_push.sh
  on:
    branch: master
