version: 0.2

phases:
  install:
   runtime-versions:
     golang: 1.15
  pre_build:
    commands:
      - aws --version
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/u7w2h8y6
  build:
    commands:
      - go build
      - go test ./...
      - export IMAGE_TAG=`cat version`
      - docker build -t public.ecr.aws/u7w2h8y6/go-hello-http:$IMAGE_TAG .
  post_build:
    commands:
      - docker push public.ecr.aws/u7w2h8y6/go-hello-http:$IMAGE_TAG
      - echo Build completed on `date`
