version: 0.2

phases:
  install: 
   runtime-versions: 
     golang: 1.14
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 391996659322.dkr.ecr.eu-central-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Go code
      - go build
      - echo Testing
      - go test ./...
      - echo Getting Tag
      - export IMAGE_TAG=`cat version`
      - echo Building the Docker image...          
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Build completed on `date`
