version: 0.2	

phases:	
  install: 	
   runtime-versions: 	
     golang: 1.14	
  build:	
    commands:	
      - git checkout master
      - git status
      - go build	
      - go test ./...	
      - git config --global user.name "AWS CodeBuild"
      - git config --global user.email "MY_NAME@example.com"
      - VERSION=`cat version`
      - git tag $VERSION
      - git push origin $VERSION
      - 'sed -i "/appVersion:/c\appVersion: ${VERSION}" helm/Chart.yaml'
      - git add . && git commit -m 'bump chart version' && git push origin master
