version: 0.2	

phases:	
  install:
    runtime-versions: 	
      golang: 1.14	
    commands:
      - git config --global credential.helper '!aws codecommit credential-helper $@'
      - git config --global credential.UseHttpPath true
  build:	
    commands:	
      - git checkout master
      - git status
      - go build	
      - go test ./...	
      - VERSION=`cat version`
      - git tag $VERSION
      - git push origin $VERSION
      - 'sed -i "/appVersion:/c\appVersion: ${VERSION}" helm/Chart.yaml'
      - git add . && git commit -m 'bump chart version' && git push origin master
