version: 0.2	

phases:	
  install: 	
   runtime-versions: 	
     golang: 1.14	
  pre_build:	
    commands:	
      - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 391996659322.dkr.ecr.eu-central-1.amazonaws.com
  build:	
    commands:	
      - go build	
      - go test ./...	
      - export IMAGE_TAG=`cat version`	
      - docker build -t 391996659322.dkr.ecr.eu-central-1.amazonaws.comgo-hello-http:$IMAGE_TAG .	
  post_build:	
    commands:	
      - echo Pushing the Docker image...	
      - docker push 391996659322.dkr.ecr.eu-central-1.amazonaws.comgo-hello-http:$IMAGE_TAG	
      - echo Build completed on `date`
